stages:
  - build
  - test

include:
  - '/test/tests/full1/.gitlab-ci.yml'
  - '/logic/preprocess-reads/.gitlab-ci.yml'
  - '/logic/rrnapred/.gitlab-ci.yml'
  - '/logic/refDb/.gitlab-ci.yml'
  - '/logic/preprocess-contigs/.gitlab-ci.yml'
  - '/logic/gene-extractor/.gitlab-ci.yml'

