rrnapred build:
  stage: build
  tags:
    - test-server
    - bash

  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*{[^!]*}.*/ && $CI_COMMIT_MESSAGE !~ /.*{rrnapred}.*/ && $CI_COMMIT_MESSAGE !~ /.*{logic}.*/

  script:
    - cd logic/rrnapred
    - sbt clean test docker:publish